// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 Platano Games

#include "Profile/PGXProfileDeviceProfileBridge.h"
#include "Profile/PGXProfileSubsystem.h"
#include "HAL/IConsoleManager.h"

// ============================================================================
// EN: Helper — Check a CVar against an expected value
// ES: Helper — Verificar un CVar contra un valor esperado
// ============================================================================

static FPGXDeviceProfileValidation CheckCVar(const FString& CVarName, const FString& ExpectedValue)
{
	FPGXDeviceProfileValidation Result;
	Result.CVarName = CVarName;
	Result.ExpectedValue = ExpectedValue;

	IConsoleVariable* CVar = IConsoleManager::Get().FindConsoleVariable(*CVarName);
	if (CVar)
	{
		Result.ActualValue = CVar->GetString();
		Result.bMatches = Result.ActualValue.Equals(ExpectedValue, ESearchCase::IgnoreCase);
	}
	else
	{
		Result.ActualValue = TEXT("(not found)");
		Result.bMatches = false;
	}

	return Result;
}

// ============================================================================
// ValidateDeviceProfiles
// ============================================================================

TArray<FPGXDeviceProfileValidation> UPGXProfileDeviceProfileBridge::ValidateDeviceProfiles(
	const UObject* /*WorldContextObject*/,
	const FPGXResolvedProfile& Profile)
{
	TArray<FPGXDeviceProfileValidation> Results;

	// EN: Validate rendering features against CVars
	// ES: Validar features de rendering contra CVars

	// Nanite
	{
		const FString Expected = (Profile.Features.Nanite.Policy == EPGXFeaturePolicy::Allowed) ? TEXT("1") : TEXT("0");
		Results.Add(CheckCVar(TEXT("r.Nanite"), Expected));
	}

	// Lumen
	{
		const FString Expected = (Profile.Features.Lumen.Policy == EPGXFeaturePolicy::Allowed) ? TEXT("1") : TEXT("0");
		Results.Add(CheckCVar(TEXT("r.Lumen.DiffuseIndirect.Allow"), Expected));
		Results.Add(CheckCVar(TEXT("r.Lumen.Reflections.Allow"), Expected));
	}

	// Ray Tracing
	{
		const FString Expected = (Profile.Features.RayTracing.Policy == EPGXFeaturePolicy::Allowed) ? TEXT("1") : TEXT("0");
		Results.Add(CheckCVar(TEXT("r.RayTracing"), Expected));
	}

	// Virtual Shadow Maps
	{
		const FString Expected = (Profile.Features.VSM.Policy == EPGXFeaturePolicy::Allowed) ? TEXT("1") : TEXT("0");
		Results.Add(CheckCVar(TEXT("r.Shadow.Virtual.Enable"), Expected));
	}

	// Virtual Textures
	{
		const FString Expected = (Profile.Features.VirtualTextures.Policy == EPGXFeaturePolicy::Allowed) ? TEXT("1") : TEXT("0");
		Results.Add(CheckCVar(TEXT("r.VirtualTextures"), Expected));
	}

	// EN: Filter to only return mismatches
	// ES: Filtrar para retornar solo discrepancias
	TArray<FPGXDeviceProfileValidation> Mismatches;
	for (const auto& R : Results)
	{
		if (!R.bMatches)
		{
			Mismatches.Add(R);
		}
	}

	return Mismatches;
}

// ============================================================================
// GenerateDeviceProfileINI
// ============================================================================

FString UPGXProfileDeviceProfileBridge::GenerateDeviceProfileINI(const FPGXResolvedProfile& Profile)
{
	FString Output;
	Output += TEXT("; ============================================================\n");
	Output += TEXT("; Auto-generated by PGX Profile System\n");
	Output += TEXT("; ============================================================\n\n");

	Output += TEXT("[/Script/Engine.RendererSettings]\n");

	// Nanite
	Output += FString::Printf(TEXT("r.Nanite=%d\n"),
		Profile.Features.Nanite.Policy == EPGXFeaturePolicy::Allowed ? 1 : 0);

	// Lumen
	const int32 LumenVal = (Profile.Features.Lumen.Policy == EPGXFeaturePolicy::Allowed) ? 1 : 0;
	Output += FString::Printf(TEXT("r.Lumen.DiffuseIndirect.Allow=%d\n"), LumenVal);
	Output += FString::Printf(TEXT("r.Lumen.Reflections.Allow=%d\n"), LumenVal);

	// Ray Tracing
	Output += FString::Printf(TEXT("r.RayTracing=%d\n"),
		Profile.Features.RayTracing.Policy == EPGXFeaturePolicy::Allowed ? 1 : 0);

	// VSM
	Output += FString::Printf(TEXT("r.Shadow.Virtual.Enable=%d\n"),
		Profile.Features.VSM.Policy == EPGXFeaturePolicy::Allowed ? 1 : 0);

	// Virtual Textures
	Output += FString::Printf(TEXT("r.VirtualTextures=%d\n"),
		Profile.Features.VirtualTextures.Policy == EPGXFeaturePolicy::Allowed ? 1 : 0);

	// Streaming pool
	if (Profile.Budgets.StreamingPool_MB > 0)
	{
		Output += FString::Printf(TEXT("r.Streaming.PoolSize=%lld\n"), Profile.Budgets.StreamingPool_MB);
	}

	return Output;
}

// ============================================================================
// Editor — PreviewCVarImpact
// ============================================================================

#if WITH_EDITOR

TArray<FPGXDeviceProfileValidation> UPGXProfileDeviceProfileBridge::PreviewCVarImpact(const FPGXResolvedProfile& Profile)
{
	TArray<FPGXDeviceProfileValidation> Results;

	// EN: Show all CVars that would be set, with current vs expected
	// ES: Mostrar todos los CVars que se establecerian, con actual vs esperado
	auto AddPreview = [&](const FString& CVarName, const FString& ExpectedValue)
	{
		Results.Add(CheckCVar(CVarName, ExpectedValue));
	};

	AddPreview(TEXT("r.Nanite"), Profile.Features.Nanite.Policy == EPGXFeaturePolicy::Allowed ? TEXT("1") : TEXT("0"));
	AddPreview(TEXT("r.Lumen.DiffuseIndirect.Allow"), Profile.Features.Lumen.Policy == EPGXFeaturePolicy::Allowed ? TEXT("1") : TEXT("0"));
	AddPreview(TEXT("r.Lumen.Reflections.Allow"), Profile.Features.Lumen.Policy == EPGXFeaturePolicy::Allowed ? TEXT("1") : TEXT("0"));
	AddPreview(TEXT("r.RayTracing"), Profile.Features.RayTracing.Policy == EPGXFeaturePolicy::Allowed ? TEXT("1") : TEXT("0"));
	AddPreview(TEXT("r.Shadow.Virtual.Enable"), Profile.Features.VSM.Policy == EPGXFeaturePolicy::Allowed ? TEXT("1") : TEXT("0"));
	AddPreview(TEXT("r.VirtualTextures"), Profile.Features.VirtualTextures.Policy == EPGXFeaturePolicy::Allowed ? TEXT("1") : TEXT("0"));

	return Results;
}

#endif
