// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 Platano Games
#pragma once
#include "CoreMinimal.h"

// EN: Log categories for PGX framework systems
// ES: Categorias de log para los sistemas del framework PGX

PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGX, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXLog, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXMessages, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXSettings, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXPool, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXData, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXTags, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXStateMachine, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXSave, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXGameFlow, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXProfile, Log, All);
PGXCORERUNTIME_API DECLARE_LOG_CATEGORY_EXTERN(LogPGXPSO, Log, All);
